### PR TITLE
add reset function

### PR DESCRIPTION
**Pull request by tomaash**
When data source of items inside infinite scroll is changed, page count does not reset automatically. So I added a function that can be called to reset page count manually.

### CODE REVIEW

**Comment by flocks** [comment]
Yep very useful @tomaash thx

**Comment by hcarreras** [comment]
Very useful 👍 ! 
Why is it not being merged?

**Comment by danbovey** [comment]
This repo isn't being maintained, there's a [fork I'm running which is very active](https://github.com/CassetteRocks/react-infinite-scroller) but it still doesn't have a reset function. It's meant to be very lightweight.

**Comment by hcarreras** [comment]
@danbovey Thanks for answering. 

I found out that the best solution is to maintain my own counter as specified in https://github.com/CassetteRocks/react-infinite-scroller/issues/12

Anyways, is good to know that is not being maintained.  Maybe you could add it to the README?
I can of course make the PR if you prefer it.

**Comment by danbovey** [comment]
I don't have access to this repo to update, that's why the fork exists 😃

**Pull request closed without merging**
